spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "http://localhost:5173,http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
