version: '3.8'

services:
  postgres:
    image: postgres:17.5
    container_name: postgres-db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: secret
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    ports:
      - '5672:5672'    # AMQP
      - '15672:15672'  # Management UI

volumes:
  pgdata:
  rabbitmqdata:
