server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "http://localhost:3000,http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

      routes:

        # ─────────────  OAUTH2 GOOGLE  ─────────────
        - id: oauth2-authorization
          uri: http://auth-service:8080
          predicates:
            - Path=/oauth2/authorization/google
          filters:
            - PreserveHostHeader

        - id: oauth2-callback
          uri: http://auth-service:8080
          predicates:
            - Path=/login/oauth2/**
          filters:
            - PreserveHostHeader

        # ─────────────  AUTH REST  ─────────────
        - id: auth-service
          uri: http://auth-service:8080
          predicates:
            - Path=/api/v1/auth/**

        # ─────────────  USER INFO / ROLES  ─────────────
        - id: user-service
          uri: http://auth-service:8080
          predicates:
            - Path=/api/v1/users/**

        # ─────────────  ANAGRAFICA – cittadini  ─────────────
        - id: anagrafica-citizens
          uri: ${ANAGRAFICA_SERVICE_URL:http://anagrafica-service:8080}
          predicates:
            - Path=/api/v1/citizens/**

        # ─────────────  ANAGRAFICA – pazienti di un medico  ─────────────
        - id: anagrafica-doctor-patients
          uri: ${ANAGRAFICA_SERVICE_URL:http://anagrafica-service:8080}
          predicates:
            - Path=/api/v1/doctors/*/patients

        # ─────────────  PRESCRIPTION  ─────────────
        - id: prescription-service
          uri: ${PRESCRIPTION_SERVICE_URL:http://prescription-service:8080}
          predicates:
            - Path=/api/v1/prescriptions/**
            - Path=/api/v1/patients/*/prescriptions/**
            - Path=/api/v1/doctors/**
            - Path=/api/v1/patients/*/drugs/**
            - Path=/api/v1/patients/*/doctors/**

        # ─────────────  PHARMA  ─────────────
        - id: pharma-service
          uri: ${PHARMA_SERVICE_URL:http://pharma-service:8080}
          predicates:
            - Path=/api/v1/drugs,/api/v1/drugs/**,
              /api/v1/active-ingredients/**,
              /api/v1/pharma-families/**

        # ─────────────  DISPENSATION  ─────────────
        - id: dispensation-service
          uri: ${DISPENSATION_SERVICE_URL:http://dispensation-service:8080}
          predicates:
            - Path=/api/v1/dispensations/**
            - Path=/api/v1/prescriptions/*/dispensations/**
            - Path=/api/v1/pharmacists/**
            - Path=/api/v1/patients/*/pharmacists/**

        # ─────────────  INVENTORY  ─────────────
        - id: inventory-service
          uri: ${INVENTORY_SERVICE_URL:http://inventory-service:8080}
          predicates:
            - Path=/api/v1/inventory/**

        # ─────────────  NOTIFICATION  ─────────────
        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URL:http://notification-service:8080}
          predicates:
            - Path=/api/v1/notifications/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
        - PreserveHostHeader