server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "http://localhost:3000,http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

      routes:

        # ─────────────  OAUTH2 GOOGLE  ─────────────
        # (1) richiesta iniziale /oauth2/authorization/google
        - id: oauth2-authorization
          uri: http://auth-service:8080      # dentro la rete Docker
          predicates:
            - Path=/oauth2/authorization/google
          filters:
            - PreserveHostHeader             # host esterno rimane “localhost:8080”

        # (2) callback /login/oauth2/**
        - id: oauth2-callback
          uri: http://auth-service:8080
          predicates:
            - Path=/login/oauth2/**
          filters:
            - PreserveHostHeader

        # ─────────────  AUTH REST  ─────────────
        - id: auth-service
          uri: http://auth-service:8080
          predicates:
            - Path=/api/v1/auth/**

        # ─────────────  PRESCRIPTION  ─────────────
        - id: prescription-service
          uri: ${PRESCRIPTION_SERVICE_URL:http://prescription-service:8080}
          predicates:
            - Path=/api/v1/prescriptions/**,/api/v1/patients/{patientId}/prescriptions/**

        # ─────────────  DISPENSATION  ─────────────
        - id: dispensation-service
          uri: ${DISPENSATION_SERVICE_URL:http://dispensation-service:8080}
          predicates:
            - Path=/api/v1/dispensations/**,/api/v1/prescriptions/*/dispensations/**

        # ─────────────  INVENTORY  ─────────────
        - id: inventory-service
          uri: ${INVENTORY_SERVICE_URL:http://inventory-service:8080}
          predicates:
            - Path=/api/v1/inventory/**

        # ─────────────  NOTIFICATION  ─────────────
        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URL:http://notification-service:8080}
          predicates:
            - Path=/api/v1/notifications/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
