server:
  port: 8084
spring:
  application:
    name: pharma-service
  datasource:
    url: jdbc:postgresql://localhost:5432/health
    username: ${DB_USER:myuser}
    password: ${DB_PASS:mypass}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    sql: debug

# Security (JWT)
jwt:
  issuer: health‑stack